# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  flightbookingapplication:
    image: flightbookingapplication
    build:
      context: .
      dockerfile: FlightBooking.Application/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - flightbooking-network

volumes:
  mssql-data:

networks:
  flightbooking-network:
    driver: bridge