version: '3.4'

services:
  flightbookingapplication:
    image: flightbookingapplication
    build:
      context: .
      dockerfile: FlightBooking.Application/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__BookingDbContext=Server=mssql;Database=FlightBooking;User=sa;Password=yourStrongPassword
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - flightbooking-network

volumes:
  mssql-data:

networks:
  flightbooking-network:
    driver: bridge
