name: Deploy Terraform State to Azure Storage

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0  # Replace with your desired Terraform version

      - name: Initialize Terraform
        run: terraform init \
          -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" \
          -backend-config="access_key=${{ secrets.AZURE_ACCESS_KEY }}" \
          -backend-config="key=terraform.tfstate"

      - name: Plan Terraform Deployment
        run: terraform plan

      - name: Apply Terraform Deployment
        run: terraform apply -auto-approve

      - name: Upload Terraform State to Azure Storage
        run: terraform state push
